In [5]:
%pip install torch

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import torch

In [6]:
print(torch.__version__)

2.3.1+cpu


## Creating Tensors

In [7]:
# using empty tensor

torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# check type of tensor
x = torch.empty(2,3)
type(x)

torch.Tensor

In [9]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
# using rand
torch.rand(2,3)

tensor([[0.9121, 0.7213, 0.0467],
        [0.2890, 0.7867, 0.9392]])

In [12]:
# manual seed - to get same random values every time we run the code it remains same
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [15]:
# using tensor
x = torch.tensor([[2.5,3],[3.4,5.6]])
x

tensor([[2.5000, 3.0000],
        [3.4000, 5.6000]])

In [20]:
# other ways to create tensor
# arange
torch.arange(0,10,0.3)

tensor([0.0000, 0.3000, 0.6000, 0.9000, 1.2000, 1.5000, 1.8000, 2.1000, 2.4000,
        2.7000, 3.0000, 3.3000, 3.6000, 3.9000, 4.2000, 4.5000, 4.8000, 5.1000,
        5.4000, 5.7000, 6.0000, 6.3000, 6.6000, 6.9000, 7.2000, 7.5000, 7.8000,
        8.1000, 8.4000, 8.7000, 9.0000, 9.3000, 9.6000, 9.9000])

In [21]:
# linspace

torch.linspace(0,20,100)

tensor([ 0.0000,  0.2020,  0.4040,  0.6061,  0.8081,  1.0101,  1.2121,  1.4141,
         1.6162,  1.8182,  2.0202,  2.2222,  2.4242,  2.6263,  2.8283,  3.0303,
         3.2323,  3.4343,  3.6364,  3.8384,  4.0404,  4.2424,  4.4444,  4.6465,
         4.8485,  5.0505,  5.2525,  5.4545,  5.6566,  5.8586,  6.0606,  6.2626,
         6.4646,  6.6667,  6.8687,  7.0707,  7.2727,  7.4747,  7.6768,  7.8788,
         8.0808,  8.2828,  8.4848,  8.6869,  8.8889,  9.0909,  9.2929,  9.4949,
         9.6970,  9.8990, 10.1010, 10.3030, 10.5051, 10.7071, 10.9091, 11.1111,
        11.3131, 11.5152, 11.7172, 11.9192, 12.1212, 12.3232, 12.5253, 12.7273,
        12.9293, 13.1313, 13.3333, 13.5354, 13.7374, 13.9394, 14.1414, 14.3434,
        14.5455, 14.7475, 14.9495, 15.1515, 15.3535, 15.5556, 15.7576, 15.9596,
        16.1616, 16.3636, 16.5657, 16.7677, 16.9697, 17.1717, 17.3737, 17.5758,
        17.7778, 17.9798, 18.1818, 18.3838, 18.5859, 18.7879, 18.9899, 19.1919,
        19.3939, 19.5960, 19.7980, 20.00

In [23]:
# using eye

torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])