In [ ]:
%pip install torch

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import torch

In [ ]:
print(torch.__version__)

2.3.1+cpu


## Creating Tensors

In [ ]:
# using empty tensor

torch.empty(2,3)

tensor([[-3.8043e+30,  9.3887e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [ ]:
# check type of tensor
x = torch.empty(2,3)
type(x)

torch.Tensor

In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.2407, 0.2360, 0.4135],
        [0.2256, 0.0208, 0.7757]])

In [ ]:
# manual seed - to get same random values every time we run the code it remains same
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
x = torch.tensor([[2.5,3],[3.4,5.6]])
x

tensor([[2.5000, 3.0000],
        [3.4000, 5.6000]])

In [ ]:
# other ways to create tensor
# arange
torch.arange(0,10,0.3)

tensor([0.0000, 0.3000, 0.6000, 0.9000, 1.2000, 1.5000, 1.8000, 2.1000, 2.4000,
        2.7000, 3.0000, 3.3000, 3.6000, 3.9000, 4.2000, 4.5000, 4.8000, 5.1000,
        5.4000, 5.7000, 6.0000, 6.3000, 6.6000, 6.9000, 7.2000, 7.5000, 7.8000,
        8.1000, 8.4000, 8.7000, 9.0000, 9.3000, 9.6000, 9.9000])

In [ ]:
# linspace

torch.linspace(0,20,100)

tensor([ 0.0000,  0.2020,  0.4040,  0.6061,  0.8081,  1.0101,  1.2121,  1.4141,
         1.6162,  1.8182,  2.0202,  2.2222,  2.4242,  2.6263,  2.8283,  3.0303,
         3.2323,  3.4343,  3.6364,  3.8384,  4.0404,  4.2424,  4.4444,  4.6465,
         4.8485,  5.0505,  5.2525,  5.4545,  5.6566,  5.8586,  6.0606,  6.2626,
         6.4646,  6.6667,  6.8687,  7.0707,  7.2727,  7.4747,  7.6768,  7.8788,
         8.0808,  8.2828,  8.4848,  8.6869,  8.8889,  9.0909,  9.2929,  9.4949,
         9.6970,  9.8990, 10.1010, 10.3030, 10.5051, 10.7071, 10.9091, 11.1111,
        11.3131, 11.5152, 11.7172, 11.9192, 12.1212, 12.3232, 12.5253, 12.7273,
        12.9293, 13.1313, 13.3333, 13.5354, 13.7374, 13.9394, 14.1414, 14.3434,
        14.5455, 14.7475, 14.9495, 15.1515, 15.3535, 15.5556, 15.7576, 15.9596,
        16.1616, 16.3636, 16.5657, 16.7677, 16.9697, 17.1717, 17.3737, 17.5758,
        17.7778, 17.9798, 18.1818, 18.3838, 18.5859, 18.7879, 18.9899, 19.1919,
        19.3939, 19.5960, 19.7980, 20.00

In [ ]:
# using eye

torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
# using full - to create tensor with same value
torch.full((2,3), 10)

tensor([[10, 10, 10],
        [10, 10, 10]])

## Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x) # create tensor with same shape as x

tensor([[2881692501872,             0,             0],
        [            0,             0,             0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

## Tensor Data Types

In [ ]:
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]], dtype=torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [ ]:
# assign data type
torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]], dtype=torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [ ]:
# using to() method to change data type

x = torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]])
x = x.to(torch.int32)

## Mathematical Operations

In [ ]:
# Scalar Operations

x = torch.rand(2,2)
x

tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])

In [ ]:
# addition
x + 2

tensor([[2.2627, 2.0428],
        [2.2080, 2.1180]])

In [ ]:
# subtraction
x - 4

tensor([[-3.7373, -3.9572],
        [-3.7920, -3.8820]])

In [ ]:
# multiplication
x * 5

tensor([[1.3135, 0.2142],
        [1.0401, 0.5902]])

In [ ]:
# division
x / 2

tensor([[0.1313, 0.0214],
        [0.1040, 0.0590]])

In [ ]:
# int division - floor division

x // 2

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
# mod
x % 2

tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])

In [ ]:
# power
x ** 2

tensor([[0.0690, 0.0018],
        [0.0433, 0.0139]])

## element wise operation

In [ ]:
a = torch.rand(2,2)
b = torch.rand(2,2)

print(a)
print(b)

tensor([[0.1217, 0.7356],
        [0.7118, 0.7876]])
tensor([[0.4183, 0.9014],
        [0.9969, 0.7565]])


In [ ]:
# add
torch.add(a,b)

tensor([[0.5400, 1.6370],
        [1.7087, 1.5441]])

In [ ]:
# subtract
torch.sub(a,b)

tensor([[-0.2966, -0.1658],
        [-0.2851,  0.0311]])

In [ ]:
# mulitply
torch.mul(a,b)

tensor([[0.0509, 0.6631],
        [0.7095, 0.5958]])

In [ ]:
# division
torch.div(a,b)

tensor([[0.2909, 0.8160],
        [0.7140, 1.0411]])

In [ ]:
# power
torch.pow(a,b)

tensor([[0.4143, 0.7582],
        [0.7125, 0.8347]])

In [ ]:
# mod

torch.fmod(a,b)

tensor([[0.1217, 0.7356],
        [0.7118, 0.0311]])

In [ ]:
c = torch.tensor([[1,-2],[3,-4]])

In [ ]:
torch.abs(c)   # absolute value

tensor([[1, 2],
        [3, 4]])

In [ ]:
# negative
torch.neg(c)

tensor([[-1,  2],
        [-3,  4]])

In [ ]:
# round
torch.round(torch.tensor(3.14))

tensor(3.)

In [ ]:
# ceil
torch.ceil(torch.tensor(3.14))

tensor(4.)

In [ ]:
# floor
torch.floor(torch.tensor(3.14))

tensor(3.)

In [ ]:
# clamp - to limit the value between min and max

torch.clamp(c, min=0, max=2)

tensor([[1, 0],
        [2, 0]])

## Reduction Operation

In [ ]:
e = torch.randint(size=(2,2), low=0, high=10)
e

tensor([[4, 3],
        [8, 7]])

In [ ]:
# sum
torch.sum(e)

tensor(22)

In [ ]:
# sum along columns
torch.sum(e, dim=0)

tensor([12, 10])

In [ ]:
# sum along rows
torch.sum(e, dim=1)

tensor([ 7, 15])

In [ ]:
# mean
torch.mean(e,dtype=torch.float32)

tensor(5.5000)

In [ ]:
# max and min
print(torch.max(e))
torch.min(e)

tensor(8)


tensor(3)

In [ ]:
# product
torch.prod(e)

tensor(672)

In [ ]:
# standard deviation
torch.std(e,dtype=torch.float32)

TypeError: std() received an invalid combination of arguments - got (Tensor, dtype=torch.dtype), but expected one of:
 * (Tensor input, tuple of ints dim, bool unbiased, bool keepdim, *, Tensor out)
 * (Tensor input, tuple of ints dim, *, Number correction, bool keepdim, Tensor out)
 * (Tensor input, bool unbiased)
      didn't match because some of the keywords were incorrect: dtype
 * (Tensor input, tuple of names dim, bool unbiased, bool keepdim, *, Tensor out)
 * (Tensor input, tuple of names dim, *, Number correction, bool keepdim, Tensor out)


In [ ]:
# variance
torch.var(e)

RuntimeError: std and var only support floating point and complex dtypes

## Matrix Operations

In [ ]:
f = torch.randint(size =(2,3) , low = 0 , high = 10)
g = torch.randint(size =(3,2) , low = 0 , high = 10)

In [ ]:
print(f)
print(g)

tensor([[4, 6, 0],
        [1, 9, 9]])
tensor([[8, 0],
        [7, 0],
        [0, 9]])


In [ ]:
# matrix multiplication
torch.mm(f,g)

tensor([[74,  0],
        [71, 81]])

In [ ]:
# dot product
torch.dot(f.view(-1),g.view(-1))

tensor(113)

In [ ]:
f.view(-1) # changes into 1D tensor

tensor([4, 6, 0, 1, 9, 9])

In [ ]:
# Transpose
f.t()

tensor([[4, 1],
        [6, 9],
        [0, 9]])

In [ ]:
# creating a square matrix using torch.rand
h = torch.rand(3,3)

In [ ]:
# determinant
torch.det(h)

tensor(-0.0543)

In [ ]:
# inverse
torch.inverse(h)

tensor([[ -1.3542,   2.0042,  -0.7611],
        [ -0.0386,   8.8635, -12.1265],
        [  1.0817,  -2.0888,   2.8227]])

## Comparision Operations

In [ ]:
# creating a square matrix using torch.rand
i = torch.rand(3,3)
j = torch.rand(3,3)

In [ ]:
# greater than
torch.gt(i,j)

tensor([[False, False, False],
        [False, False,  True],
        [False, False,  True]])

In [ ]:
# less than
torch.lt(i,j)

tensor([[ True,  True,  True],
        [ True,  True, False],
        [ True,  True, False]])

In [ ]:
# equal to
torch.eq(i,j)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [ ]:
# not equal to
torch.ne(i,j)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [ ]:
# greater than or equal to
torch.ge(i,j)

tensor([[False, False, False],
        [False, False,  True],
        [False, False,  True]])

In [ ]:
# less than or equal to
torch.le(i,j)

tensor([[ True,  True,  True],
        [ True,  True, False],
        [ True,  True, False]])

## Special Functions

In [ ]:
# log
torch.log(torch.tensor(2.0))

tensor(0.6931)

In [ ]:
# exp
torch.exp(torch.tensor(2.0))

tensor(7.3891)

In [ ]:
# sqrt
torch.sqrt(torch.tensor(2.0))

tensor(1.4142)

In [ ]:
# sigmopid
torch.sigmoid(torch.tensor(2.0))

tensor(0.8808)

In [ ]:
# softmax
torch.softmax(torch.tensor([1.0,2.0,3.0]), dim=0)

tensor([0.0900, 0.2447, 0.6652])

In [ ]:
# relu
torch.relu(torch.tensor(-2.0))

tensor(0.)

## Inplace Operations

In [ ]:
# inplace operations - operations that modify the tensor in place and end with _    eg. add_ , sub_ , mul_ , div_ , pow_

k = torch.rand(2,2)
l  = torch.rand(2,2)

In [ ]:
k.add_(l) # inplace addition

tensor([[1.4317, 1.3515],
        [1.5412, 1.2557]])

In [ ]:
k.relu_() # inplace relu

tensor([[1.4317, 1.3515],
        [1.5412, 1.2557]])

## copying a tensor

In [ ]:
a = torch.rand(2,2)
a

tensor([[0.2170, 0.9454],
        [0.7116, 0.1157]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.2170, 0.9454],
        [0.7116, 0.1157]])

In [ ]:
a [0][0] = 1

In [ ]:
b

tensor([[1.0000, 0.9454],
        [0.7116, 0.1157]])

In [ ]:
id(a)

1315571738624

In [ ]:
id(b)

1315571738624

In [ ]:
b = a.clone()

In [ ]:
id(a)

1315571738624

In [ ]:
id(b)

1315572260672

## Working with GPUs

In [3]:
torch.cuda.is_available()

device = torch.device('cuda')

In [4]:
# Creating a new tensor on GPU
torch.rand((2,3), device = device)


tensor([[0.5394, 0.1430, 0.1442],
        [0.7464, 0.7341, 0.3412]], device='cuda:0')

In [5]:
# moving an existing tensor on GPU

a = torch.rand(2,3)

In [8]:
b = a.to(device)
b

tensor([[0.1321, 0.2240, 0.1400],
        [0.3155, 0.4122, 0.6741]], device='cuda:0')