In [1]:
import torch

In [2]:
x = torch.tensor(3.0, requires_grad=True)

In [3]:
y = x**2 

In [4]:
print(x)
print(y)

tensor(3., requires_grad=True)
tensor(9., grad_fn=<PowBackward0>)


In [5]:
y.backward()

In [6]:
x.grad


tensor(6.)

In [7]:
x = torch.tensor(3.0, requires_grad=True)

In [8]:
y = x**2    

In [9]:
z = torch.sin(y)

In [10]:
x

tensor(3., requires_grad=True)

In [11]:
y

tensor(9., grad_fn=<PowBackward0>)

In [12]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [13]:
z.backward()

In [14]:
x.grad

tensor(-5.4668)

In [15]:
# neural network differentiation

x = torch.tensor(6.7)  # Input Feature
y = torch.tensor(0.0)  # True label ( binary )

w = torch.tensor(1.0)  # Weight
b = torch.tensor(0.0)  # Bias

In [16]:
# Binary Cross Entropy Loss for scalar
def binary_cross_entropy_loss(prediction , target):
    epsilon = 1e-12 # to avoid log(0)
    prediction = torch.clamp(prediction, epsilon, 1.0 - epsilon)
    return - (target * torch.log(prediction) + (1.0 - target) * torch.log(1.0 - prediction))

In [17]:
# Forward pass

z = w * x + b # weighted sum 
y_pred = torch.sigmoid(z) # sigmoid activation function , which shows predicted probability


# computer binary cross entropy loss

loss = binary_cross_entropy_loss(y_pred, y)

loss

tensor(6.7012)

In [18]:
#  Derivatives

# 1. dL/d(y_pred) : Loss with respect to y_pred

dloss_dy_pred = ( y_pred - y ) / ( y_pred * ( 1 - y_pred ) )

# 2. dy_pred/dz : y_pred with respect to z

dy_pred_dz = y_pred * ( 1 - y_pred )

# 3. dz/dw : z with respect to w

dz_dw = x # dz/dw = x

# 4. dz/db : z with respect to b

dz_db = 1 # dz/db = 1 


dl_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dl_db = dloss_dy_pred * dy_pred_dz * dz_db

In [19]:
print(f"Manual gradient of loss with respect to w : {dl_dw}")
print(f"Manual gradient of loss with respect to b : {dl_db}")

Manual gradient of loss with respect to w : 6.691762447357178
Manual gradient of loss with respect to b : 0.998770534992218


In [21]:
x = torch.tensor(6.7)  # Input Feature
y = torch.tensor(0.0)  # True label ( binary )

w = torch.tensor(1.0, requires_grad=True)  # Weight
b = torch.tensor(0.0, requires_grad=True)  # Bias 

In [22]:
 w

tensor(1., requires_grad=True)

In [23]:
b

tensor(0., requires_grad=True)

In [24]:
z = w * x + b # weighted sum
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [25]:
y_pred = torch.sigmoid(z) # sigmoid activation function , which shows predicted probability
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [26]:
loss = binary_cross_entropy_loss(y_pred, y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [27]:
loss.backward()

In [28]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(0.9988)


In [29]:
x = torch.tensor([6.7, 4.5, 3.3], requires_grad=True)  # Input Feature

In [30]:
x

tensor([6.7000, 4.5000, 3.3000], requires_grad=True)

In [31]:
y = ( x ** 2 ).mean()
y

tensor(25.3433, grad_fn=<MeanBackward0>)

In [32]:
y.backward()

In [33]:
x.grad

tensor([4.4667, 3.0000, 2.2000])

In [34]:
 # clearning gradients
x.grad.zero_()

tensor([0., 0., 0.])

In [35]:
# disable gradient tracking
# option 1 - requires_grad_(False)
# option 2 - detach()
# option 3 - with torch.no_grad():



In [36]:
# 1 

x.requires_grad_(False)

tensor([6.7000, 4.5000, 3.3000])

In [37]:
x

tensor([6.7000, 4.5000, 3.3000])

In [38]:
# 2 

x = torch.tensor([6.7, 4.5, 3.3], requires_grad=True)  # Input Feature
x = x.detach()

In [40]:
 # 3
 with torch.no_grad():
        x = torch.tensor([6.7, 4.5, 3.3], requires_grad=True)  # Input Feature
        y = ( x ** 2 ).mean()
        y.backward()
        print(x.grad)

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn