In [ ]:
import torch

## Code flow

1) Load dataset
2) Basic preprocessing
3) Training process \
        - Create the model \
        - Forward pass \
        - Loss calculation \
        - Backpropagation \
        - Parameters update 
4) Model evaluation

In [2]:
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [8]:
df.shape

(569, 33)

In [9]:
df.drop(columns =['id', 'Unnamed: 32'], inplace = True)

In [10]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### Train - Test Split

In [11]:
X_train, X_test,y_train,y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size = 0.2)

In [12]:
scaling = StandardScaler()
X_train = scaling.fit_transform(X_train)
X_test = scaling.transform(X_test)

In [13]:
X_train

array([[-0.62851592, -1.09375665, -0.56716361, ..., -0.82306781,
        -0.28075323,  1.10414123],
       [ 1.73672701,  1.74272271,  1.67344618, ...,  0.8535049 ,
         0.4092993 , -0.20218864],
       [-0.13353048, -0.06978989, -0.103011  , ...,  0.40858718,
        -0.25308603,  0.26257929],
       ...,
       [-0.51320681, -0.66634195, -0.52299754, ..., -0.4214145 ,
        -0.45814881, -0.41797376],
       [-1.08975236, -0.65262811, -1.06853021, ..., -0.47158281,
        -0.3393426 ,  0.61668819],
       [-0.93225699,  1.09131529, -0.94421092, ..., -1.2492683 ,
         0.25957092, -0.40856774]])

In [14]:
y_train

145    B
260    M
423    B
218    M
442    B
      ..
4      M
487    M
74     B
547    B
549    B
Name: diagnosis, Length: 455, dtype: object

In [15]:
# Label Encoding

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [16]:
y_train

array([0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,

In [ ]:
# Changing to tensor ( Numpy )
x_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [18]:
x_train_tensor

tensor([[-0.6285, -1.0938, -0.5672,  ..., -0.8231, -0.2808,  1.1041],
        [ 1.7367,  1.7427,  1.6734,  ...,  0.8535,  0.4093, -0.2022],
        [-0.1335, -0.0698, -0.1030,  ...,  0.4086, -0.2531,  0.2626],
        ...,
        [-0.5132, -0.6663, -0.5230,  ..., -0.4214, -0.4581, -0.4180],
        [-1.0898, -0.6526, -1.0685,  ..., -0.4716, -0.3393,  0.6167],
        [-0.9323,  1.0913, -0.9442,  ..., -1.2493,  0.2596, -0.4086]],
       dtype=torch.float64)

In [19]:
y_train_tensor.shape

torch.Size([455])

## Defining the model 

In [36]:
class MySimpleNN:
    def __init__(self, X):
        self.weights = torch.randn(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):  # Ensure proper indentation
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

## Important parameters

In [37]:
learning_rate = 0.1
epochs = 25

In [38]:
# Traning Pipeline

model = MySimpleNN(x_train_tensor)
model.weights

tensor([[-1.0520],
        [ 0.0551],
        [ 0.9760],
        [-0.2120],
        [-0.8755],
        [ 1.9721],
        [-0.5706],
        [ 1.1723],
        [-0.7588],
        [ 0.3769],
        [ 1.5527],
        [ 1.1168],
        [-0.4196],
        [ 0.4343],
        [ 0.0371],
        [-1.1013],
        [-0.3359],
        [-0.4140],
        [-3.4587],
        [ 0.0809],
        [-0.1794],
        [ 0.7594],
        [ 0.0290],
        [ 0.2679],
        [ 0.8910],
        [ 0.9070],
        [ 1.3054],
        [ 1.4678],
        [-1.1512],
        [-1.1532]], dtype=torch.float64, requires_grad=True)

In [39]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [40]:
for epoch in range(epochs):
    # Forward pass
    y_pred = model.forward(x_train_tensor)
    print(y_pred)

tensor([[1.7710e-05],
        [9.9976e-01],
        [7.8364e-01],
        [9.9819e-01],
        [3.5290e-01],
        [1.2827e-03],
        [9.9858e-01],
        [9.1592e-01],
        [5.6286e-04],
        [8.8331e-02],
        [1.4104e-02],
        [2.2123e-03],
        [9.9957e-01],
        [6.7281e-02],
        [9.9971e-01],
        [1.0000e+00],
        [6.5299e-01],
        [1.9753e-02],
        [1.8325e-03],
        [9.8442e-01],
        [9.2680e-01],
        [1.0665e-02],
        [4.0976e-04],
        [3.3158e-02],
        [1.6476e-01],
        [4.2557e-01],
        [9.9980e-01],
        [9.8955e-01],
        [3.0520e-02],
        [1.0000e+00],
        [4.6794e-01],
        [9.9861e-01],
        [6.5010e-07],
        [1.0000e+00],
        [9.1780e-01],
        [9.7287e-01],
        [9.9986e-01],
        [9.4671e-01],
        [9.9469e-01],
        [7.3875e-01],
        [6.3532e-01],
        [4.4660e-03],
        [9.9598e-01],
        [1.9993e-01],
        [1.2409e-01],
        [3