In [ ]:
import torch

## Code flow

1) Load dataset
2) Basic preprocessing
3) Training process \
        - Create the model \
        - Forward pass \
        - Loss calculation \
        - Backpropagation \
        - Parameters update 
4) Model evaluation

In [2]:
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [8]:
df.shape

(569, 33)

In [9]:
df.drop(columns =['id', 'Unnamed: 32'], inplace = True)

In [10]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### Train - Test Split

In [11]:
X_train, X_test,y_train,y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size = 0.2)

In [12]:
scaling = StandardScaler()
X_train = scaling.fit_transform(X_train)
X_test = scaling.transform(X_test)

In [13]:
X_train

array([[-0.62851592, -1.09375665, -0.56716361, ..., -0.82306781,
        -0.28075323,  1.10414123],
       [ 1.73672701,  1.74272271,  1.67344618, ...,  0.8535049 ,
         0.4092993 , -0.20218864],
       [-0.13353048, -0.06978989, -0.103011  , ...,  0.40858718,
        -0.25308603,  0.26257929],
       ...,
       [-0.51320681, -0.66634195, -0.52299754, ..., -0.4214145 ,
        -0.45814881, -0.41797376],
       [-1.08975236, -0.65262811, -1.06853021, ..., -0.47158281,
        -0.3393426 ,  0.61668819],
       [-0.93225699,  1.09131529, -0.94421092, ..., -1.2492683 ,
         0.25957092, -0.40856774]])

In [14]:
y_train

145    B
260    M
423    B
218    M
442    B
      ..
4      M
487    M
74     B
547    B
549    B
Name: diagnosis, Length: 455, dtype: object

In [15]:
# Label Encoding

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [16]:
y_train

array([0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,

In [ ]:
# Changing to tensor ( Numpy )
x_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [18]:
x_train_tensor

tensor([[-0.6285, -1.0938, -0.5672,  ..., -0.8231, -0.2808,  1.1041],
        [ 1.7367,  1.7427,  1.6734,  ...,  0.8535,  0.4093, -0.2022],
        [-0.1335, -0.0698, -0.1030,  ...,  0.4086, -0.2531,  0.2626],
        ...,
        [-0.5132, -0.6663, -0.5230,  ..., -0.4214, -0.4581, -0.4180],
        [-1.0898, -0.6526, -1.0685,  ..., -0.4716, -0.3393,  0.6167],
        [-0.9323,  1.0913, -0.9442,  ..., -1.2493,  0.2596, -0.4086]],
       dtype=torch.float64)

In [19]:
y_train_tensor.shape

torch.Size([455])

## Defining the model 

In [41]:
class MySimpleNN:
    def __init__(self, X):
        self.weights = torch.randn(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):  # Ensure proper indentation
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self,y_pred,y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon,1.0-epsilon)
        # calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss
        

## Important parameters

In [42]:
learning_rate = 0.1
epochs = 25

In [43]:
# Traning Pipeline

model = MySimpleNN(x_train_tensor)
model.weights

tensor([[-1.3260],
        [-0.4585],
        [ 0.4892],
        [-0.2544],
        [ 0.3168],
        [-0.6875],
        [ 0.1911],
        [-0.0608],
        [-1.8562],
        [ 1.3223],
        [ 0.9686],
        [ 0.1632],
        [-0.0904],
        [-1.4563],
        [-0.6446],
        [-0.7831],
        [-0.0897],
        [ 0.4569],
        [ 1.0721],
        [ 0.8931],
        [-2.5064],
        [ 0.8070],
        [-1.4365],
        [-1.0842],
        [-0.2795],
        [ 0.7866],
        [-1.2251],
        [ 0.3283],
        [ 0.9366],
        [ 0.6532]], dtype=torch.float64, requires_grad=True)

In [44]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [56]:
for epoch in range(epochs):
    # Forward pass
    y_pred = model.forward(x_train_tensor)
    
    # loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)
    
    # backward pass 

    loss.backward()
    # parameters update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad
    
    # zero the gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    
    print(f'epoch : {epoch + 1} , loss : {loss.item()}')

epoch : 1 , loss : 0.8152089782026783
epoch : 2 , loss : 0.8139174717011338
epoch : 3 , loss : 0.8126427940860714
epoch : 4 , loss : 0.8113844074289279
epoch : 5 , loss : 0.8101418083163712
epoch : 6 , loss : 0.8089145245830295
epoch : 7 , loss : 0.8077021124574244
epoch : 8 , loss : 0.8065041540588764
epoch : 9 , loss : 0.8053202551933358
epoch : 10 , loss : 0.8041500434045346
epoch : 11 , loss : 0.8029931662438785
epoch : 12 , loss : 0.8018492897283479
epoch : 13 , loss : 0.8007180969605299
epoch : 14 , loss : 0.7995992868889651
epoch : 15 , loss : 0.7984925731903643
epoch : 16 , loss : 0.7973976832580797
epoch : 17 , loss : 0.7963143572835658
epoch : 18 , loss : 0.7952423474195445
epoch : 19 , loss : 0.7941814170152339
epoch : 20 , loss : 0.7931313399153981
epoch : 21 , loss : 0.7920918998161286
epoch : 22 , loss : 0.7910628896712603
epoch : 23 , loss : 0.7900441111441416
epoch : 24 , loss : 0.7890353741001878
epoch : 25 , loss : 0.7880364961362283


In [57]:
model.bias

tensor([-0.5908], dtype=torch.float64, requires_grad=True)

In [58]:
model.weights

tensor([[-0.4442],
        [-0.4738],
        [ 1.3367],
        [ 0.6041],
        [ 0.2158],
        [-0.6381],
        [ 0.5130],
        [ 0.3693],
        [-1.3467],
        [ 0.4388],
        [ 1.3480],
        [-0.2331],
        [ 0.1561],
        [-0.9535],
        [-0.5517],
        [-0.8703],
        [-0.0734],
        [ 0.4310],
        [ 0.4181],
        [ 0.3520],
        [-1.6338],
        [ 0.7084],
        [-0.6173],
        [-0.2062],
        [-0.2066],
        [ 0.7521],
        [-1.0056],
        [ 0.6434],
        [ 0.7241],
        [ 0.0486]], dtype=torch.float64, requires_grad=True)

In [62]:
# evaluation

with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy : {accuracy.item()}')

Accuracy : 0.5393967628479004


In [ ]:
..