In [7]:
import torch

## Code flow

1) Load dataset
2) Basic preprocessing
3) Training process \
        - Create the model \
        - Forward pass \
        - Loss calculation \
        - Backpropagation \
        - Parameters update 
4) Model evaluation

In [8]:
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [9]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [10]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [11]:
df.shape

(569, 33)

In [12]:
df.drop(columns =['id', 'Unnamed: 32'], inplace = True)

In [13]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### Train - Test Split

In [14]:
X_train, X_test,y_train,y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size = 0.2)

In [15]:
scaling = StandardScaler()
X_train = scaling.fit_transform(X_train)
X_test = scaling.transform(X_test)

In [16]:
X_train

array([[-1.22631309, -1.68131227, -1.24691266, ..., -1.75867012,
         0.33514853, -0.15200231],
       [-0.88819844, -0.38959723, -0.86316428, ..., -0.25992075,
        -1.00719546, -0.07988146],
       [-0.22967727, -0.79197218, -0.23228998, ...,  0.83727748,
         1.02935093,  0.98886994],
       ...,
       [ 1.34191946,  1.20389901,  1.19461107, ...,  1.21420664,
         1.73506854,  0.493678  ],
       [-0.07473112, -0.01922938, -0.14227988, ..., -0.51997147,
        -0.89697849, -0.46320091],
       [ 1.24231122, -0.5039083 ,  1.17050122, ...,  0.78560171,
        -0.01195268,  0.02120129]])

In [17]:
y_train

140    B
534    B
81     B
208    B
143    B
      ..
251    B
138    M
87     M
481    B
121    M
Name: diagnosis, Length: 455, dtype: object

In [18]:
# Label Encoding

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [19]:
y_train

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,

In [20]:
# Changing to tensor ( Numpy )
x_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [21]:
x_train_tensor

tensor([[-1.2263, -1.6813, -1.2469,  ..., -1.7587,  0.3351, -0.1520],
        [-0.8882, -0.3896, -0.8632,  ..., -0.2599, -1.0072, -0.0799],
        [-0.2297, -0.7920, -0.2323,  ...,  0.8373,  1.0294,  0.9889],
        ...,
        [ 1.3419,  1.2039,  1.1946,  ...,  1.2142,  1.7351,  0.4937],
        [-0.0747, -0.0192, -0.1423,  ..., -0.5200, -0.8970, -0.4632],
        [ 1.2423, -0.5039,  1.1705,  ...,  0.7856, -0.0120,  0.0212]],
       dtype=torch.float64)

In [22]:
y_train_tensor.shape

torch.Size([455])

## Defining the model 

In [23]:
class MySimpleNN:
    def __init__(self, X):
        self.weights = torch.randn(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):  # Ensure proper indentation
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self,y_pred,y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon,1.0-epsilon)
        # calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss
        

## Important parameters

In [24]:
learning_rate = 0.1
epochs = 25

In [25]:
# Traning Pipeline

model = MySimpleNN(x_train_tensor)
model.weights

tensor([[-0.8275],
        [-1.3042],
        [ 0.4763],
        [-0.1614],
        [ 1.3287],
        [-0.9585],
        [ 0.3103],
        [ 0.4523],
        [-0.1702],
        [ 1.7630],
        [ 0.8611],
        [ 0.6621],
        [ 0.4106],
        [ 0.5017],
        [ 1.1141],
        [ 0.3545],
        [ 0.5868],
        [-1.6454],
        [-0.3192],
        [ 0.9864],
        [ 1.6413],
        [-0.2915],
        [ 1.7313],
        [ 0.3907],
        [ 1.1314],
        [-0.5677],
        [-0.7056],
        [-0.1394],
        [-0.4870],
        [-1.3219]], dtype=torch.float64, requires_grad=True)

In [26]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [27]:
for epoch in range(epochs):
    # Forward pass
    y_pred = model.forward(x_train_tensor)
    print(y_pred)

tensor([[4.9082e-01],
        [2.8489e-01],
        [1.9237e-01],
        [7.4818e-03],
        [2.8148e-02],
        [2.6188e-01],
        [5.2635e-02],
        [9.1132e-01],
        [3.9720e-01],
        [9.4927e-01],
        [2.6878e-01],
        [8.1009e-01],
        [4.1061e-01],
        [7.5579e-01],
        [9.9999e-01],
        [9.8771e-02],
        [8.2397e-01],
        [2.8924e-02],
        [7.9950e-02],
        [6.8276e-02],
        [2.8461e-02],
        [9.6648e-01],
        [9.0585e-01],
        [9.6191e-03],
        [3.1536e-01],
        [2.0447e-01],
        [1.2345e-02],
        [3.8144e-01],
        [9.3630e-01],
        [4.2674e-01],
        [9.9997e-01],
        [9.9946e-01],
        [7.9465e-01],
        [2.2683e-03],
        [1.1679e-02],
        [9.8296e-01],
        [4.3257e-01],
        [4.1021e-01],
        [1.3874e-01],
        [4.6606e-03],
        [2.7172e-02],
        [8.9152e-01],
        [5.9985e-01],
        [5.3949e-01],
        [3.2609e-01],
        [3

In [28]:
# loss calculate

loss = model.loss_function(y_pred, y_train_tensor)
print(f'epoch : {epoch + 1} , loss : {loss}')

epoch : 25 , loss : 1.8908085157795884


In [29]:
# backward pass 

loss.backward()

In [30]:
# parameters update
with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad
    
# zero the gradients
model.weights.grad.zero_()
model.bias.grad.zero_()
print(f'epoch : {epoch + 1} , loss : {loss.item()}')

epoch : 25 , loss : 1.8908085157795884


In [32]:
# create model
model = MySimpleNN(x_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(x_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 2.0868451880105177
Epoch: 2, Loss: 1.987018177023343
Epoch: 3, Loss: 1.8933798566133229
Epoch: 4, Loss: 1.8072644827398836
Epoch: 5, Loss: 1.7286901911222419
Epoch: 6, Loss: 1.6576107530638748
Epoch: 7, Loss: 1.5938686626265899
Epoch: 8, Loss: 1.537163129645549
Epoch: 9, Loss: 1.4870528318347687
Epoch: 10, Loss: 1.4429805063731977
Epoch: 11, Loss: 1.4042966420078764
Epoch: 12, Loss: 1.3702879343559171
Epoch: 13, Loss: 1.3402277951791095
Epoch: 14, Loss: 1.31343708534898
Epoch: 15, Loss: 1.2893261551456365
Epoch: 16, Loss: 1.2674085485183058
Epoch: 17, Loss: 1.2472956067433434
Epoch: 18, Loss: 1.2286828836852626
Epoch: 19, Loss: 1.2113346379269159
Epoch: 20, Loss: 1.1950692355517285
Epoch: 21, Loss: 1.1797465935104063
Epoch: 22, Loss: 1.1652579529267497
Epoch: 23, Loss: 1.1515178493375653
Epoch: 24, Loss: 1.1384579677379134
Epoch: 25, Loss: 1.1260225319085175
