In [2]:
import torch
import torch.nn as nn

In [3]:
# create a model class
class Model(nn.Module):
    
    def __init__(self,num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self,features):
        out = self.linear(features)
        out = self.sigmoid(out)
        
        return out
    
        

In [5]:
# create a dataset

features = torch.rand(10,5)
features

tensor([[1.6529e-01, 2.7286e-01, 7.9583e-01, 8.0422e-01, 4.1674e-01],
        [1.6822e-01, 9.9941e-01, 6.6365e-01, 3.5339e-01, 7.7787e-01],
        [9.5136e-01, 1.2846e-01, 9.8970e-01, 8.9300e-01, 6.4087e-01],
        [8.2286e-01, 9.9497e-01, 6.1079e-01, 8.9043e-04, 5.7538e-01],
        [4.6932e-01, 2.1429e-01, 1.7369e-02, 7.6158e-01, 2.7005e-01],
        [5.1432e-01, 4.7359e-01, 5.4528e-01, 6.1251e-01, 6.8749e-01],
        [7.3790e-01, 3.1015e-02, 2.2664e-01, 5.1816e-01, 1.7308e-01],
        [3.7223e-01, 3.4421e-01, 2.5924e-01, 1.7148e-01, 9.6861e-01],
        [9.2269e-01, 9.2076e-01, 1.4720e-01, 3.0429e-03, 3.7433e-01],
        [4.0131e-01, 3.8879e-01, 7.6767e-01, 3.0612e-01, 1.8644e-01]])

In [7]:
# create a model
model = Model(features.shape[1])
print(model)
model(features)

Model(
  (linear): Linear(in_features=5, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)


tensor([[0.6422],
        [0.6684],
        [0.6297],
        [0.6155],
        [0.6552],
        [0.6538],
        [0.6001],
        [0.6288],
        [0.6197],
        [0.5861]], grad_fn=<SigmoidBackward0>)

In [8]:
# show model weights

print(model.linear.weight)

Parameter containing:
tensor([[-0.0731,  0.2952, -0.1850,  0.4292,  0.1969]], requires_grad=True)


In [9]:
# show model bias

print(model.linear.bias)

Parameter containing:
tensor([0.2363], requires_grad=True)


In [10]:
%pip install torchinfo

Note: you may need to restart the kernel to use updated packages.


In [12]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [13]:
# constructing a model with multiple layers
# 18 weifghts and 3 biases , hidden layer - relu activation function, output layer - sigmoid activation function

class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self,features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        
        return out