In [1]:
# Problems with previous approaches :- 
# Memory Inefficient
# Better Convergence 
# currently we using batch gradient descent :-
#   - It is slow
#   - It is memory inefficient
#   - It is not parallelizable
#   - It is sensitive to feature scaling

# solution - using batches of data to update the weights  & train the model

In [16]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset
import torchvision.transforms as transforms
from torch.utils.data import DataLoader


In [17]:
from sklearn.datasets import make_classification


In [18]:
# step 1 - create a synthetic dataset using sklearn
X,y = make_classification(
    n_samples = 10 , # number of samples
    n_features=2, # number of features
    n_classes=2, # number of classes
    n_informative=2, # number of informative features
    n_redundant=0, # number of redundant features
    random_state=42 # random seed
)

In [19]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [20]:
X.shape

(10, 2)

In [21]:
X = torch.tensor(X).float()
y = torch.tensor(y).float()

In [22]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [23]:
y

tensor([1., 0., 0., 0., 0., 1., 1., 1., 1., 0.])

In [27]:
class CustomDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y
        
    def __len__(self):
        return len(self.X)
    
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]
    
    


In [28]:
dataset = CustomDataset(X, y)

In [29]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [30]:
for batch_features, batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("_"*50)

tensor([[-0.7206, -0.9606],
        [ 1.7273, -1.1858]])
tensor([0., 1.])
__________________________________________________
tensor([[-0.9382, -0.5430],
        [-0.5872, -1.9717]])
tensor([1., 0.])
__________________________________________________
tensor([[ 1.0683, -0.9701],
        [ 1.8997,  0.8344]])
tensor([1., 1.])
__________________________________________________
tensor([[ 1.7774,  1.5116],
        [-1.1402, -0.8388]])
tensor([1., 0.])
__________________________________________________
tensor([[-1.9629, -0.9923],
        [-2.8954,  1.9769]])
tensor([0., 0.])
__________________________________________________
